services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:v3.3.1
    container_name: mlflow_server
    links:
      - jupyter
    ports:
        - "5001:5000"
    volumes:
        - ../db:/mlflow/db            # Database location
        - ../artifacts:/artifacts     # Separate location for artifacts
        - ./init-mlflow.sh:/init-mlflow.sh
    restart: always
    user: "0:0"  # Run as root
    environment:
      - MLFLOW_BACKEND_STORE_URI=sqlite:////mlflow/db/mlflow.db
      - MLFLOW_DEFAULT_ARTIFACT_ROOT=/artifacts
    command: ["bash", "/init-mlflow.sh"]

  jupyter:
    image: jupyter/minimal-notebook:latest
    container_name: jupyter_lab
    ports:
      - "8888:8888"
    volumes:
      - ../artifacts:/artifacts 
      - ../notebooks:/home/jovyan/work
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - AZURE_OPENAI_ENDPOINT=${AZURE_OPENAI_ENDPOINT}
      - AZURE_OPENAI_API_KEY=${AZURE_OPENAI_API_KEY}
      - OPENAI_API_VERSION=${OPENAI_API_VERSION}
      - AZURE_DEPLOYMENT_NAME=${AZURE_DEPLOYMENT_NAME}
      - OPENAI_API_TYPE=${OPENAI_API_TYPE}
    command: start-notebook.sh --NotebookApp.token='' --NotebookApp.password='' --NotebookApp.allow_root=True

  bonsai:
      build:
        context: ..
        dockerfile: docker/Dockerfile.api
      ports:
        - "3000:3000"
      environment:
        - MLFLOW_TRACKING_URI=http://mlflow:5000
        - AZURE_OPENAI_ENDPOINT=${AZURE_OPENAI_ENDPOINT}
        - AZURE_OPENAI_API_KEY=${AZURE_OPENAI_API_KEY}
        - OPENAI_API_VERSION=${OPENAI_API_VERSION}
        - AZURE_DEPLOYMENT_NAME=${AZURE_DEPLOYMENT_NAME}
      volumes:
        - ../artifacts:/artifacts  
        - ../api:/app/api
      command: ["python", "/app/api/bonsai_app.py"]
      healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
        interval: 30s
        timeout: 10s
        retries: 3
      restart: always
      depends_on:
        - mlflow

volumes:
  mlflow_data:
